name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0
      - run: pnpm install --shamefully-hoist
      - run: pnpm lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0
      - run: pnpm install --shamefully-hoist
      - run: pnpm test
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0
      - run: pnpm install --shamefully-hoist
      - run: pnpm typecheck
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.5.0
      - run: pnpm install --shamefully-hoist
      - run: pnpm generate
